#!/bin/bash

## uninstall configuration files via stow 

STOW_DIR=$HOME/.dotfiles; export STOW_DIR

all_stows=$(for dir in $HOME/.dotfiles/*/; do basename $dir; done) ; 
echo "found stows '$(echo $all_stows)' in '$STOW_DIR'"

for curr_stow in $all_stows; do 
  echo "stowing $curr_stow"
  stow -D $curr_stow 
done;

unset STOW_DIR

